In [4]:
print("hello")

hello


# 00. PyTorch fundamentals

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` 

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back ad Python int
scalar.item()

7

In [9]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Randow tensor are important because the way many neural networks learn is that they start with full of random number and then adjust those random numbers to better represent the data.

`Start with random number -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

In [20]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1730, 0.3894, 0.3999, 0.7893],
        [0.0845, 0.4345, 0.3184, 0.8203],
        [0.5654, 0.3906, 0.3791, 0.5978]])

In [21]:
random_tensor.ndim

2

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # H,W,C
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
torch.rand(3,3)

tensor([[0.8947, 0.3683, 0.1696],
        [0.6625, 0.2554, 0.5997],
        [0.8090, 0.5339, 0.3715]])

### Zeros and Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [29]:
# Use torch.range()
one_to_ten= torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
# Create tensor like
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype


**Note:** tensor datatype is one of the 3 big errors you'll run into with PyTorch & Deep learning :
1. Tensors not right datatype 
2. Tensors not right shape
3. Tensors not on the right device

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor 
                               device="cpu", # What device is your tensor on
                               requires_grad=False) # whether or not to track gradient with the tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
floate_16_tensor = float_32_tensor.type(torch.float16)
floate_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
floate_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get data type from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from tensor, can use `tensor.device`


In [37]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2712, 0.7354, 0.0129, 0.3371],
        [0.3904, 0.9849, 0.2116, 0.3971],
        [0.1077, 0.1865, 0.3127, 0.2758]])

In [38]:
some_tensor.size()

torch.Size([3, 4])

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.2712, 0.7354, 0.0129, 0.3371],
        [0.3904, 0.9849, 0.2116, 0.3971],
        [0.1077, 0.1865, 0.3127, 0.2758]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multriplication

In [40]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
tensor - 10

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-build function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication

Two main way of performing multiplication in neural network and deep learning

1. element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rule thatperforming matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimentsion**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [45]:
# Element wise multiplication
print(tensor, "*" , tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
# Matrix multiplication
torch.matmul(tensor , tensor)

tensor(14)

In [47]:
# Matrix multriplication by hand
1*1 + 2*2 + 3*3 

14

In [48]:
%%time
value = 0
for i in range (len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [49]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common in deep learning: shape errors

In [50]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A , tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [51]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix pur tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.
A **transpose** switches the axes or dimentions of a given tensor

In [52]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [53]:
tensor_B , tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [55]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [56]:
# Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [57]:
# Find the mean
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
# Find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin() , x[0]

(tensor(0), tensor(0))

In [61]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax() , x[9]

(tensor(9), tensor(90))

## Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimentions from a tensor
* Unsqueeze - add a `1` dimention to a target tensor
* Permute - return a view of the input with dimentions permuted (swaped) in a certain way

In [62]:
# Let's create a tensor
import torch 
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
# Add an extra dimention
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# Chcnge the view
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Changeging z changes x (because a view of a tensor share the same memory as the original
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [67]:
# torch.squeeze() - remove all single dimentions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
x_reshaped.shape

torch.Size([1, 9])

In [69]:
x_squeezed = x_reshaped.squeeze()

In [70]:
x_squeezed.shape

torch.Size([9])

In [71]:
x_squeezed.unsqueeze(dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
x_squeezed.unsqueeze(dim=0).shape

torch.Size([1, 9])

In [73]:
# torch.permute - rearanges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3))

# Permute the original tensor to rearange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) 

x_original.shape , x_permuted.shape 

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [74]:
x_original[0,0,0] = 728218
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [75]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
x[0,0]

tensor([1, 2, 3])

In [78]:
x[0,0,0]

tensor(1)

In [79]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing libraly.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [80]:
%pip install numpy

DEPRECATION: Loading egg at c:\python312\lib\site-packages\vboxapi-1.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [81]:
import torch
import numpy as np

print(np.__version__)  # This should print the version of NumPy

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

2.2.1


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
# Change the value of array, what will this do to `tensor`
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:
numpy_tensor.dtype

dtype('float32')

## Reproducibility (trying to take random out of random)

In short how Neural Networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavou" the randomness.

In [85]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3403, 0.2031, 0.4740, 0.9974],
        [0.2615, 0.2079, 0.3880, 0.8525],
        [0.7268, 0.6216, 0.4199, 0.3995]])
tensor([[0.0833, 0.0438, 0.5230, 0.8262],
        [0.8264, 0.3137, 0.6171, 0.3855],
        [0.4993, 0.6976, 0.4708, 0.7887]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [86]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thank to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU 

1. Easiest - Use google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - take a little bit of setup and requires the investment of purchasing GPU.
3. Use clous computing - GCP , AWS , Azure 

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.

In [94]:
!nvidia-smi

Mon Jan  6 17:35:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070      WDDM  |   00000000:08:00.0  On |                  N/A |
|  0%   48C    P8             29W /  224W |    1983MiB /   8192MiB |     37%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [88]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [95]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [90]:
# Count number of device
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [91]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3] , device="cpu")

# Tesor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [92]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transfer it to NumPy
# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

: 